import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }) {
  console.log('NEXT_PUBLIC_ENV', process.env.NEXT_PUBLIC_TEST);
  console.log('WITHOUT_NEXT_PUBLIC_ENV', process.env.TEST);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>INDEX: {data.name}</h1>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const response = await fetch(`https://test-v0.vercel.app/api/hello`);
  const result = await response.json();

  return {
    props: {
      data: result,
    },
  };
};
